export const SITE_STATIC_PATHS = ['', 'privacy', 'terms']
export const SITE_TITLE = 'Tu MVP en 1 Semana'
export const SITE_DESCRIPTION = 'Desarrollamos tu producto mínimo viable en solo 7 días. Valida tu idea de negocio rápidamente con un MVP funcional y listo para el mercado.'
export const SITE_NAME = 'MVP Sprint'
export const SITE_COMPANY = 'Coderoot'

export const MAKE_WEBHOOK_URL = "https://hook.eu1.make.com/9hfv9gelaoj39d8nlxn9r9t3s28gunsv"

export const PRODUCT_TYPES = [
    { value: 'app-fitness', label: 'App de Fitness / Gimnasio', budgetMultiplier: 1.2 },
    { value: 'ecommerce', label: 'E-commerce / Tienda Online', budgetMultiplier: 1.0 },
    { value: 'saas', label: 'SaaS / Plataforma Web', budgetMultiplier: 1.3 },
    { value: 'marketplace', label: 'Marketplace', budgetMultiplier: 1.4 },
    { value: 'app-delivery', label: 'App de Delivery', budgetMultiplier: 1.2 },
    { value: 'crm', label: 'CRM / Gestión de Clientes', budgetMultiplier: 1.1 },
    { value: 'booking', label: 'Sistema de Reservas', budgetMultiplier: 1.0 },
    { value: 'social', label: 'Red Social / Comunidad', budgetMultiplier: 1.5 },
    { value: 'fintech', label: 'Fintech / Pagos', budgetMultiplier: 1.6 },
    { value: 'healthcare', label: 'Salud / Telemedicina', budgetMultiplier: 1.4 },
    { value: 'education', label: 'EdTech / Educación', budgetMultiplier: 1.1 },
    { value: 'other', label: 'Otro (especificar)', budgetMultiplier: 1.0 },
]

export const BUDGET_RANGES = [
    { value: '0-3000', label: 'Menos de 3.000€', baseAmount: 2000 },
    { value: '3000-5000', label: '3.000€ - 5.000€', baseAmount: 4000 },
    { value: '5000-10000', label: '5.000€ - 10.000€', baseAmount: 7500 },
    { value: '10000-15000', label: '10.000€ - 15.000€', baseAmount: 12500 },
    { value: '15000-25000', label: '15.000€ - 25.000€', baseAmount: 20000 },
    { value: '25000+', label: '+25.000€', baseAmount: 30000 },
]

export const COUNTRIES = [
    { code: 'AF', phonePrefix: '+93', name: 'Afghanistan' },
    { code: 'AL', phonePrefix: '+355', name: 'Albania' },
    { code: 'DZ', phonePrefix: '+213', name: 'Algeria' },
    { code: 'AS', phonePrefix: '+1-684', name: 'American Samoa' },
    { code: 'AD', phonePrefix: '+376', name: 'Andorra' },
    { code: 'AO', phonePrefix: '+244', name: 'Angola' },
    { code: 'AG', phonePrefix: '+1-268', name: 'Antigua and Barbuda' },
    { code: 'AR', phonePrefix: '+54', name: 'Argentina' },
    { code: 'AM', phonePrefix: '+374', name: 'Armenia' },
    { code: 'AU', phonePrefix: '+61', name: 'Australia' },
    { code: 'AT', phonePrefix: '+43', name: 'Austria' },
    { code: 'AZ', phonePrefix: '+994', name: 'Azerbaijan' },
    { code: 'BS', phonePrefix: '+1-242', name: 'Bahamas' },
    { code: 'BH', phonePrefix: '+973', name: 'Bahrain' },
    { code: 'BD', phonePrefix: '+880', name: 'Bangladesh' },
    { code: 'BB', phonePrefix: '+1-246', name: 'Barbados' },
    { code: 'BY', phonePrefix: '+375', name: 'Belarus' },
    { code: 'BE', phonePrefix: '+32', name: 'Belgium' },
    { code: 'BZ', phonePrefix: '+501', name: 'Belize' },
    { code: 'BJ', phonePrefix: '+229', name: 'Benin' },
    { code: 'BT', phonePrefix: '+975', name: 'Bhutan' },
    { code: 'BO', phonePrefix: '+591', name: 'Bolivia' },
    { code: 'BA', phonePrefix: '+387', name: 'Bosnia and Herzegovina' },
    { code: 'BW', phonePrefix: '+267', name: 'Botswana' },
    { code: 'BR', phonePrefix: '+55', name: 'Brazil' },
    { code: 'BN', phonePrefix: '+673', name: 'Brunei' },
    { code: 'BG', phonePrefix: '+359', name: 'Bulgaria' },
    { code: 'BF', phonePrefix: '+226', name: 'Burkina Faso' },
    { code: 'BI', phonePrefix: '+257', name: 'Burundi' },
    { code: 'KH', phonePrefix: '+855', name: 'Cambodia' },
    { code: 'CM', phonePrefix: '+237', name: 'Cameroon' },
    { code: 'CA', phonePrefix: '+1', name: 'Canada' },
    { code: 'CV', phonePrefix: '+238', name: 'Cape Verde' },
    { code: 'CF', phonePrefix: '+236', name: 'Central African Republic' },
    { code: 'TD', phonePrefix: '+235', name: 'Chad' },
    { code: 'CL', phonePrefix: '+56', name: 'Chile' },
    { code: 'CN', phonePrefix: '+86', name: 'China' },
    { code: 'CO', phonePrefix: '+57', name: 'Colombia' },
    { code: 'KM', phonePrefix: '+269', name: 'Comoros' },
    { code: 'CG', phonePrefix: '+242', name: 'Congo' },
    { code: 'CR', phonePrefix: '+506', name: 'Costa Rica' },
    { code: 'HR', phonePrefix: '+385', name: 'Croatia' },
    { code: 'CU', phonePrefix: '+53', name: 'Cuba' },
    { code: 'CY', phonePrefix: '+357', name: 'Cyprus' },
    { code: 'CZ', phonePrefix: '+420', name: 'Czech Republic' },
    { code: 'DK', phonePrefix: '+45', name: 'Denmark' },
    { code: 'DJ', phonePrefix: '+253', name: 'Djibouti' },
    { code: 'DM', phonePrefix: '+1-767', name: 'Dominica' },
    { code: 'DO', phonePrefix: '+1-809', name: 'Dominican Republic' },
    { code: 'EC', phonePrefix: '+593', name: 'Ecuador' },
    { code: 'EG', phonePrefix: '+20', name: 'Egypt' },
    { code: 'SV', phonePrefix: '+503', name: 'El Salvador' },
    { code: 'GQ', phonePrefix: '+240', name: 'Equatorial Guinea' },
    { code: 'ER', phonePrefix: '+291', name: 'Eritrea' },
    { code: 'EE', phonePrefix: '+372', name: 'Estonia' },
    { code: 'ET', phonePrefix: '+251', name: 'Ethiopia' },
    { code: 'FJ', phonePrefix: '+679', name: 'Fiji' },
    { code: 'FI', phonePrefix: '+358', name: 'Finland' },
    { code: 'FR', phonePrefix: '+33', name: 'France' },
    { code: 'GA', phonePrefix: '+241', name: 'Gabon' },
    { code: 'GM', phonePrefix: '+220', name: 'Gambia' },
    { code: 'GE', phonePrefix: '+995', name: 'Georgia' },
    { code: 'DE', phonePrefix: '+49', name: 'Germany' },
    { code: 'GH', phonePrefix: '+233', name: 'Ghana' },
    { code: 'GR', phonePrefix: '+30', name: 'Greece' },
    { code: 'GD', phonePrefix: '+1-473', name: 'Grenada' },
    { code: 'GT', phonePrefix: '+502', name: 'Guatemala' },
    { code: 'GN', phonePrefix: '+224', name: 'Guinea' },
    { code: 'GW', phonePrefix: '+245', name: 'Guinea-Bissau' },
    { code: 'GY', phonePrefix: '+592', name: 'Guyana' },
    { code: 'HT', phonePrefix: '+509', name: 'Haiti' },
    { code: 'HN', phonePrefix: '+504', name: 'Honduras' },
    { code: 'HU', phonePrefix: '+36', name: 'Hungary' },
    { code: 'IS', phonePrefix: '+354', name: 'Iceland' },
    { code: 'IN', phonePrefix: '+91', name: 'India' },
    { code: 'ID', phonePrefix: '+62', name: 'Indonesia' },
    { code: 'IR', phonePrefix: '+98', name: 'Iran' },
    { code: 'IQ', phonePrefix: '+964', name: 'Iraq' },
    { code: 'IE', phonePrefix: '+353', name: 'Ireland' },
    { code: 'IL', phonePrefix: '+972', name: 'Israel' },
    { code: 'IT', phonePrefix: '+39', name: 'Italy' },
    { code: 'JM', phonePrefix: '+1-876', name: 'Jamaica' },
    { code: 'JP', phonePrefix: '+81', name: 'Japan' },
    { code: 'JO', phonePrefix: '+962', name: 'Jordan' },
    { code: 'KZ', phonePrefix: '+7', name: 'Kazakhstan' },
    { code: 'KE', phonePrefix: '+254', name: 'Kenya' },
    { code: 'KI', phonePrefix: '+686', name: 'Kiribati' },
    { code: 'KP', phonePrefix: '+850', name: 'North Korea' },
    { code: 'KR', phonePrefix: '+82', name: 'South Korea' },
    { code: 'KW', phonePrefix: '+965', name: 'Kuwait' },
    { code: 'KG', phonePrefix: '+996', name: 'Kyrgyzstan' },
    { code: 'LA', phonePrefix: '+856', name: 'Laos' },
    { code: 'LV', phonePrefix: '+371', name: 'Latvia' },
    { code: 'LB', phonePrefix: '+961', name: 'Lebanon' },
    { code: 'LS', phonePrefix: '+266', name: 'Lesotho' },
    { code: 'LR', phonePrefix: '+231', name: 'Liberia' },
    { code: 'LY', phonePrefix: '+218', name: 'Libya' },
    { code: 'LI', phonePrefix: '+423', name: 'Liechtenstein' },
    { code: 'LT', phonePrefix: '+370', name: 'Lithuania' },
    { code: 'LU', phonePrefix: '+352', name: 'Luxembourg' },
    { code: 'MG', phonePrefix: '+261', name: 'Madagascar' },
    { code: 'MW', phonePrefix: '+265', name: 'Malawi' },
    { code: 'MY', phonePrefix: '+60', name: 'Malaysia' },
    { code: 'MV', phonePrefix: '+960', name: 'Maldives' },
    { code: 'ML', phonePrefix: '+223', name: 'Mali' },
    { code: 'MT', phonePrefix: '+356', name: 'Malta' },
    { code: 'MH', phonePrefix: '+692', name: 'Marshall Islands' },
    { code: 'MR', phonePrefix: '+222', name: 'Mauritania' },
    { code: 'MU', phonePrefix: '+230', name: 'Mauritius' },
    { code: 'MX', phonePrefix: '+52', name: 'Mexico' },
    { code: 'FM', phonePrefix: '+691', name: 'Micronesia' },
    { code: 'MD', phonePrefix: '+373', name: 'Moldova' },
    { code: 'MC', phonePrefix: '+377', name: 'Monaco' },
    { code: 'MN', phonePrefix: '+976', name: 'Mongolia' },
    { code: 'ME', phonePrefix: '+382', name: 'Montenegro' },
    { code: 'MA', phonePrefix: '+212', name: 'Morocco' },
    { code: 'MZ', phonePrefix: '+258', name: 'Mozambique' },
    { code: 'MM', phonePrefix: '+95', name: 'Myanmar' },
    { code: 'NA', phonePrefix: '+264', name: 'Namibia' },
    { code: 'NR', phonePrefix: '+674', name: 'Nauru' },
    { code: 'NP', phonePrefix: '+977', name: 'Nepal' },
    { code: 'NL', phonePrefix: '+31', name: 'Netherlands' },
    { code: 'NZ', phonePrefix: '+64', name: 'New Zealand' },
    { code: 'NI', phonePrefix: '+505', name: 'Nicaragua' },
    { code: 'NE', phonePrefix: '+227', name: 'Niger' },
    { code: 'NG', phonePrefix: '+234', name: 'Nigeria' },
    { code: 'NO', phonePrefix: '+47', name: 'Norway' },
    { code: 'OM', phonePrefix: '+968', name: 'Oman' },
    { code: 'PK', phonePrefix: '+92', name: 'Pakistan' },
    { code: 'PW', phonePrefix: '+680', name: 'Palau' },
    { code: 'PA', phonePrefix: '+507', name: 'Panama' },
    { code: 'PG', phonePrefix: '+675', name: 'Papua New Guinea' },
    { code: 'PY', phonePrefix: '+595', name: 'Paraguay' },
    { code: 'PE', phonePrefix: '+51', name: 'Peru' },
    { code: 'PH', phonePrefix: '+63', name: 'Philippines' },
    { code: 'PL', phonePrefix: '+48', name: 'Poland' },
    { code: 'PT', phonePrefix: '+351', name: 'Portugal' },
    { code: 'QA', phonePrefix: '+974', name: 'Qatar' },
    { code: 'RO', phonePrefix: '+40', name: 'Romania' },
    { code: 'RU', phonePrefix: '+7', name: 'Russia' },
    { code: 'RW', phonePrefix: '+250', name: 'Rwanda' },
    { code: 'WS', phonePrefix: '+685', name: 'Samoa' },
    { code: 'SM', phonePrefix: '+378', name: 'San Marino' },
    { code: 'ST', phonePrefix: '+239', name: 'Sao Tome and Principe' },
    { code: 'SA', phonePrefix: '+966', name: 'Saudi Arabia' },
    { code: 'SN', phonePrefix: '+221', name: 'Senegal' },
    { code: 'RS', phonePrefix: '+381', name: 'Serbia' },
    { code: 'SC', phonePrefix: '+248', name: 'Seychelles' },
    { code: 'SL', phonePrefix: '+232', name: 'Sierra Leone' },
    { code: 'SG', phonePrefix: '+65', name: 'Singapore' },
    { code: 'SK', phonePrefix: '+421', name: 'Slovakia' },
    { code: 'SI', phonePrefix: '+386', name: 'Slovenia' },
    { code: 'SB', phonePrefix: '+677', name: 'Solomon Islands' },
    { code: 'SO', phonePrefix: '+252', name: 'Somalia' },
    { code: 'ZA', phonePrefix: '+27', name: 'South Africa' },
    { code: 'SS', phonePrefix: '+211', name: 'South Sudan' },
    { code: 'ES', phonePrefix: '+34', name: 'Spain' },
    { code: 'LK', phonePrefix: '+94', name: 'Sri Lanka' },
    { code: 'SD', phonePrefix: '+249', name: 'Sudan' },
    { code: 'SR', phonePrefix: '+597', name: 'Suriname' },
    { code: 'SZ', phonePrefix: '+268', name: 'Swaziland' },
    { code: 'SE', phonePrefix: '+46', name: 'Sweden' },
    { code: 'CH', phonePrefix: '+41', name: 'Switzerland' },
    { code: 'SY', phonePrefix: '+963', name: 'Syria' },
    { code: 'TW', phonePrefix: '+886', name: 'Taiwan' },
    { code: 'TJ', phonePrefix: '+992', name: 'Tajikistan' },
    { code: 'TZ', phonePrefix: '+255', name: 'Tanzania' },
    { code: 'TH', phonePrefix: '+66', name: 'Thailand' },
    { code: 'TL', phonePrefix: '+670', name: 'Timor-Leste' },
    { code: 'TG', phonePrefix: '+228', name: 'Togo' },
    { code: 'TO', phonePrefix: '+676', name: 'Tonga' },
    { code: 'TT', phonePrefix: '+1-868', name: 'Trinidad and Tobago' },
    { code: 'TN', phonePrefix: '+216', name: 'Tunisia' },
    { code: 'TR', phonePrefix: '+90', name: 'Turkey' },
    { code: 'TM', phonePrefix: '+993', name: 'Turkmenistan' },
    { code: 'UG', phonePrefix: '+256', name: 'Uganda' },
    { code: 'UA', phonePrefix: '+380', name: 'Ukraine' },
    { code: 'AE', phonePrefix: '+971', name: 'United Arab Emirates' },
    { code: 'GB', phonePrefix: '+44', name: 'United Kingdom' },
    { code: 'US', phonePrefix: '+1', name: 'United States' },
    { code: 'UY', phonePrefix: '+598', name: 'Uruguay' },
    { code: 'UZ', phonePrefix: '+998', name: 'Uzbekistan' },
    { code: 'VU', phonePrefix: '+678', name: 'Vanuatu' },
    { code: 'VA', phonePrefix: '+379', name: 'Vatican City' },
    { code: 'VE', phonePrefix: '+58', name: 'Venezuela' },
    { code: 'VN', phonePrefix: '+84', name: 'Vietnam' },
    { code: 'YE', phonePrefix: '+967', name: 'Yemen' },
    { code: 'ZM', phonePrefix: '+260', name: 'Zambia' },
    { code: 'ZW', phonePrefix: '+263', name: 'Zimbabwe' },
]
